### ISSUE TITLE
Can't show second Logical device number ?

### ISSUE THREAD

**Issue by crosscross** [kumy/Parse-Arcconf#1]
Hi

My arcconf has two Logical devices, but Parse-Arcconf only shows first number of 0.

as follows:

Logical device number 0
   Logical device name                      : RAID1
   RAID level                               : 1
   Status of logical device                 : Optimal

Logical device number 1
   Logical device name                      : volume
   RAID level                               : Simple_volume

Results:
'logical drive' => {
                                        '0' => {
                                                       xxxxxxxxxxxxxx
                                                }
                       }, 

Any ideas.

best regards,
## 

@sycross

**Comment by kumy** [comment]
Hi sycross,

I don't have such controller anymore.

Could you please provide the complete output of the command: `arcconf GETCONFIG 1`

Thx
Mât

**Comment by crosscross** [comment]
Hi

Here :  https://raw.githubusercontent.com/sycross/arcconf/master/GETCONFIG

Many Thanks,

@sycross

**Comment by crosscross** [comment]
Hi

Any ideas?

Many Thanks

**Comment by kumy** [comment]
Sorry, forgot this issue.

Could you please try with the new commit ? 9c56b158d07424c3848a5ee8e69139dc649e1329
